name: Bug Report
description: Report a bug or issue with the n8n Synology package
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us resolve the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have checked the [documentation](https://github.com/josedacosta/n8n-synology-package/blob/main/README.md)
          required: true
        - label: I have run the diagnostic script (`/var/packages/n8n/target/diagnose.sh`)
          required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: dropdown
    id: dsm-version
    attributes:
      label: DSM Version
      description: What version of DSM are you running?
      options:
        - DSM 7.0
        - DSM 7.1
        - DSM 7.2
        - DSM 7.3
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: What version of the n8n Synology package are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: input
    id: n8n-version
    attributes:
      label: n8n Version
      description: What version of n8n is running? (Check from n8n UI or docker-compose.yml)
      placeholder: e.g., 1.20.0
    validations:
      required: false

  - type: dropdown
    id: installation-method
    attributes:
      label: Installation Method
      description: How did you install the package?
      options:
        - Manual Install (Package Center)
        - Upgrade from previous version
        - Fresh installation
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Please provide relevant logs. You can find them at:
        - `/tmp/n8n_install.log` - Installation logs
        - `/tmp/n8n_service.log` - Service logs
        - Docker Compose logs: `cd /var/packages/n8n/target && docker-compose logs`
        - Diagnostic report: `sudo bash /var/packages/n8n/target/diagnose.sh`
      placeholder: Paste logs here
      render: shell
    validations:
      required: false

  - type: textarea
    id: container-status
    attributes:
      label: Container Status
      description: |
        Output of: `cd /var/packages/n8n/target && docker-compose ps`
      placeholder: Paste container status here
      render: shell
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: |
        Any additional environment details:
        - Synology NAS model
        - RAM available
        - Docker/Container Manager version
        - Network configuration (reverse proxy, custom ports, etc.)
      placeholder: Additional environment information
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, error messages, etc.)
      placeholder: Any additional information
    validations:
      required: false